use_frameworks!

target 'ImageLoader_circular_Example' do
  pod 'ImageLoader_circular', :path => '../'
  pod 'SDWebImage', '~> 4.1.0'
  target 'ImageLoader_circular_Tests' do
    inherit! :search_paths

    
  end
end
